#!/bin/bash
#SBATCH --job-name="prsice"
#SBATCH --cpus-per-task=24
#SBATCH --mem=32G

base_path="/home/fabbonda/projects/uosa/Silvia_Paracchini/shared/shared_resources/data_PRS/base"
target_path="/home/fabbonda/scratch/private/20220130_GWAS_grip_best_worst_Filippo/prs/alspac_data_ready"
output_path="/home/fabbonda/scratch/private/20220130_GWAS_grip_best_worst_Filippo/prs/29122021/results_2023"
prs_path="/home/fabbonda/scratch/tools/PRSice2"
pheno_file="/home/fabbonda/scratch/private/20220130_GWAS_grip_best_worst_Filippo/quant.hand.10102021.full.sample"

set -e

for base_pheno in $(cat list_phenotypes.txt)
do

echo -e "Work on $pheno and $base_pheno"

Rscript PRSice.R --dir . \
--thread 12 \
--prsice PRSice_linux \
--base $base_path/$base_pheno.chrpos.gz \
--target $pheno_file \
--score std \
--allow-inter \
--snp ID \
--binary-target F \
--pvalue P \
--pheno $pheno_file \
--keep /home/fabbonda/scratch/private/keep_general_no_sib.PLINK.txt \
--nonfounders \
--pheno-col ${pheno}.hand \
--cov $pheno_file \
--cov-col sex,age_grip \
--cov-factor sex \
--out ${pheno}.${base_pheno} \
--fastscore \
--no-full \
--extract ${pheno}.${base_pheno}.valid
